import Link from "next/link";



export default function LinkLayout({ children, }: { children: React.ReactNode }) {
    return (
        <main className="min-h-full">
            {children}
            <p className="text-center mt-12 text-sm">Site generated by <span className="underline"><Link href='/'>CryTec</Link></span></p>
        </main>
    )
}